#!/bin/sh

logger "$BUTTON pressed for $SEEN seconds"

[ "$1" = "reboot" ] && {
	echo "REBOOT" > /dev/console
	sync
	reboot
}

[ "$1" = "reset" ] && {
	echo "FACTORY RESET" > /dev/console
	jffs2reset -y && reboot &
}
