#!/bin/sh
[ -f /etc/banner ] && cat /etc/banner
[ -f /usr/bin/fortune ] \
	&& echo -e "Tips:" \
	&& /usr/bin/fortune | awk '{print "  " $0}' \
	&& echo ""

export PATH=/usr/bin:/usr/sbin:/bin:/sbin:/usr/local/bin:/usr/local/sbin
export HOME=$(grep -e "^${USER:-root}:" /etc/passwd | cut -d ":" -f 6)
export HOME=${HOME:-/root}
export PS1='\u@\h:\w\$ '

[ -x /bin/more ] || alias more=less
[ -x /usr/bin/vim ] && alias vi=vim || alias vim=vi
[ -x /bin/ls ] && alias ll='ls -l' && alias lh='ls -lh' \
				&& alias li='ls -i' && alias la='ls -a' && l='ls -F'

[ -z "$KSH_VERSION" -o \! -s /etc/mkshrc ] || . /etc/mkshrc

[ -x /usr/bin/arp ] || arp() { cat /proc/net/arp; }
[ -x /usr/bin/ldd ] || ldd() { LD_TRACE_LOADED_OBJECTS=1 $*; }
